DROP TABLE IF EXISTS cart_products;

DROP TABLE IF EXISTS cart;

DROP TABLE IF EXISTS uid_token;

DROP TABLE IF EXISTS order_products;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS suppliers;

DROP TABLE IF EXISTS users;